### ISSUE TITLE
[BUG] CMake Include guard only works on first invocation

### ISSUE THREAD

**Issue by henric-jungheim** [NXPmicro/mcux-sdk#15]
**Describe the bug**
Since the [CMake ](https://cmake.org/) include guard flags are cached, they will be retained across CMake invocations until the cache is cleared.  Therefore, they only work correctly on the first invocation.

**To Reproduce**
Run CMake, make a change to a CMakeLists.txt file (e.g., adding a new source file), then run CMake again without clearing the cache.  This is the normal behavior when using tools like [Visual Studio Code](https://code.visualstudio.com/).

**Expected behavior**
Running CMake repeatedly without clearing the cache should work.  Changing the guards from something like this:
``` CMake
if(NOT DRIVER_TRNG_INCLUDED)
    set(DRIVER_TRNG_INCLUDED true CACHE BOOL "driver_trng component is included.")
   ...
endif()
```
to this:
``` CMake
include_guard(GLOBAL)
set(DRIVER_TRNG_INCLUDED true CACHE BOOL "driver_trng component is included." FORCE)
message("driver_trng component is included.")
   ...
```
should work (assuming it is desirable to have a flag appear in the cache as before).  Using a [message()](https://cmake.org/cmake/help/latest/command/message.html) here is useful since it makes it obvious to anyone inspecting the build log which components are included.  Be aware that should the user remove an "include()", the flag will remain in the cache until it is removed (manually or by clearing the cache).

To work with CMake versions older than 3.10 (released in 2017) that do not support [include_guard()](https://cmake.org/cmake/help/latest/command/include_guard.html), this could be used instead:
``` CMake
if(DRIVER_TRNG_INCLUDED_GUARD)
    return()
endif()
set(DRIVER_TRNG_INCLUDED_GUARD TRUE)
set(DRIVER_TRNG_INCLUDED true CACHE BOOL "driver_trng component is included." FORCE)
message("driver_trng component is included.")
    ...
```
Since the ```DRIVER_TRNG_INCLUDED_GUARD``` flag is not written to the cache, it will not persist across invocations.

Note that reporting the component's version number in the message and/or cache variable could also be helpful.

**Comment by mcuxsusan** [comment]
Hi @henric-jungheim, thank you for reporting this issue and suggesting the resolution. We have tried the solution and it works as expected, we plan to go the way which uses include_guard() and upgrade the cmake minimum version to 3.10.0. The fix will come soon.
