### ISSUE TITLE
Add into cmakelist option to print memory usage in %

### ISSUE THREAD

**Issue by Hadatko** [NXPmicro/mcux-sdk#17]
**Is your enhancement proposal related to a problem? Please describe.**
I think users generally appreciate this information.

**Describe the solution you'd like**
Add following lines to the CmakeList by default.
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -Wl,--print-memory-usage")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -Wl,--print-memory-usage")
![image](https://user-images.githubusercontent.com/13130700/114680812-d8101380-9d0d-11eb-9591-6f16ee9c6792.png)

**Describe alternatives you've considered**
-

**Additional context**
Ussually i think i saw this output in other IDEs (i may be wrong). I think i saw it also in MCUXpresso IDE (not sure if i had to check some option there).

**Comment by mcuxsusan** [comment]
The improvement sounds good, checking with the team about your proposal. Appreciate for your always input!

**Comment by mcuxsusan** [comment]
Status update: the improvement has been done and will deploy in next MCUX SDK mainline release, which plans in mid July.

**Comment by Hadatko** [comment]
Thank you very much ;)
