### ISSUE TITLE
Fixing  -Wo-address-of-packed-member warnings (armgcc >= 9)

### ISSUE THREAD

**Issue by Hadatko** [NXPmicro/mcux-sdk#23]
**Is your enhancement proposal related to a problem? Please describe.**
From armgcc version 9 code belllow is fixing -Wo-address-of-packed-member warnings. Files are not present in repository.

**Describe the solution you'd like**
Use temporary variable for getting output data.
`srtm_pmic_service.c`
![image](https://user-images.githubusercontent.com/13130700/122567147-a76b9380-d048-11eb-9722-2f95a8508725.png)
![image](https://user-images.githubusercontent.com/13130700/122567202-b5211900-d048-11eb-962b-f2d1afa8a30b.png)

`srtm_rtc_service.c`
![image](https://user-images.githubusercontent.com/13130700/122567381-e4378a80-d048-11eb-8247-d17bf228c43f.png)
![image](https://user-images.githubusercontent.com/13130700/122567499-04ffe000-d049-11eb-8686-69450e9a01d7.png)

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20210618_143229](https://user-images.githubusercontent.com/13130700/122567074-93279680-d048-11eb-80cb-02a34cef30ac.png)

**Comment by mcuxsusan** [comment]
@Hadatko, thanks for raising the issue. This file is distributed in mcux-sdk-examples project and not inside this core project. For example, you may find the srtm_pmic_service.c at link https://github.com/NXPmicro/mcux-sdk-examples/blob/main/evkmcimx7ulp/demo_apps/power_mode_switch/srtm/services/srtm_pmic_service.c.

I will ask developer to check if your fix is OK. Appreciate for your contribution.

**Comment by Hadatko** [comment]
@mcuxsusan Thank you for quick response. I forgot the other repository. I will create PR there and i am closing this. I was confused by: https://github.com/NXPmicro/mcux-sdk/tree/main/components/srtm/services

**Comment by Hadatko** [comment]
Closing as PR was created: 
https://github.com/NXPmicro/mcux-sdk-examples/pull/3
