### ISSUE TITLE
[BUG] Application freeze in DbgConsole_Flush when many bigger messages are sent

### ISSUE THREAD

**Issue by Hadatko** [NXPmicro/mcux-sdk#28]
**Describe the bug**
Here is modified example for imx7ulp [erpc_matrix_multiply_rpmsg_rtos_imxcm4.zip](https://github.com/NXPmicro/mcux-sdk/files/6831754/erpc_matrix_multiply_rpmsg_rtos_imxcm4.zip).  Changes are in `source/main_core1.c` and cmake related files (flags for release target 
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \
    -DPRINTF_ADVANCED_ENABLE=1 \
    -D__FILENAME__='\"$(notdir $(abspath $<))\"' \)
 Zip file contains also `release` dir with built binaries. If few printf are removed from modification, program is working. But with all modification program will freeze.

**To Reproduce**
![image](https://user-images.githubusercontent.com/13130700/125972700-3fb41d20-d85b-4f4d-bcd8-b365d00013e4.png)
described above

**Expected behavior**
To not freeze at printf function.

**Screenshots and console output**
![image](https://user-images.githubusercontent.com/13130700/125972936-379f666a-05bf-4a18-a71d-f285e220b3d3.png)

**Comment by Hadatko** [comment]
Without this modification `-DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \` demo works. So combination usage of this macro and a many big prints usage result in app freeze.

**Comment by Hadatko** [comment]
I think putting DbgConsole_Flush after printf when this macro is used made it freezing too.

**Comment by mcuxsusan** [comment]
Hi @Hadatko, thank you for reporting the issue. To summarize the situation, do you mean that:
1. The demo in package works fine. 
2. With modification of flags.cmake for release target, adding macro definition 
-DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING
-DPRINTF_ADVANCED_ENABLE=1
-D__FILENAME__='"$(notdir $(abspath $<))"' ),  the application run to freeze.
3.  Without modification of -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING in flags.cmake, the demo works.

So, the key point may be: using -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING in flags.cmake makes the demo run to freeze. And when uses -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING,  reduce use of printf or adding DbgConsole_Flush after printf both could improve the situation and demo works. Please help clarify if my understanding is correct. Appreciate for your energetic contribution. For your information, you could also follow the guide in https://github.com/NXPmicro/mcux-sdk/#overview to obtain the whole GitHub SDK distribution via zephyr west tool, then you could be able to also get the examples delivery in https://github.com/NXPmicro/mcux-sdk-examples/ and no need to MCUXpresso SDK package to reproduce your issue.

**Comment by Hadatko** [comment]
Hi @mcuxsusan , The main issue is combination of -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING and many printf function in main_core1.c. Using DbgConsole_Flush freezing too may be additional or same issue. Not sure, but in current state not important.

**Comment by mcuxsusan** [comment]
@lylezhu2014, may you please help comment on the situation?

**Comment by Hadatko** [comment]
Any news here?

**Comment by mcuxsusan** [comment]
Hi @Hadatko, thanks for your patience. @lylezhu2014, please help update your progress here.

**Comment by lylezhu2014** [comment]
Hi  Hadatko,

The PRINTF and DbgConsole_Flush should be called in task context. Because FreeRTOS resource is used by debug console.

**Comment by Hadatko** [comment]
Thank you very much. I moved more context into tasks and rest i removed. This is working well.
