### ISSUE TITLE
Board EVK1050 is missing

### ISSUE THREAD

**Issue by mmahadevan108** [NXPmicro/mcux-sdk#50]
**Is your enhancement proposal related to a problem? Please describe.**
The Zephyr HAL requires EVK 1050 in the list of supported boards

**Describe the solution you'd like**
Add support for EVK 1050 board

**Comment by mmahadevan108** [comment]
cc @mcuxsusan

**Comment by mcuxsusan** [comment]
Hi @mmahadevan108 , thanks for raising the issue. Will add the support and create PR soon.

**Comment by mmahadevan108** [comment]
@mcuxsusan. This is not an issue. It is present as `evkbimxrt1050`. I missed it. Closing this issue.

**Comment by mcuxsusan** [comment]
Thanks for your double check.
I thought you were asking for the legacy board support evkmimxrt1050, yes, now it's suggested to use evkbimxrt1050 board and this support is already in mcux-sdk.
