### ISSUE TITLE
Lpm.c is using only rtos functions with dynamicly allocated space.

### ISSUE THREAD

**Issue by Hadatko** [NXPmicro/mcux-sdk#8]
**Is your enhancement proposal related to a problem? Please describe.**
Hi, as i am reworking application to use static api only i have to modified lpm.c file 

**Describe the solution you'd like**
Ability to use static allocation api if chosen
![image](https://user-images.githubusercontent.com/13130700/110862034-43a23380-82bf-11eb-9468-bf4056d2d187.png)
![image](https://user-images.githubusercontent.com/13130700/110862083-5288e600-82bf-11eb-8ffa-f2ef27599c4e.png)

**Describe alternatives you've considered**
-

**Additional context**
Similar to #7

**Comment by nxp-susan** [comment]
Hi @Hadatko, thank you for the advice. The lpm.c file you mentioned in this issue is not included in current MCUXpresso SDK project. I will forward to develop team to check, appreciate for your patience.

**Comment by Hadatko** [comment]
Hi @nxp-susan , no problem. I am preparing one more issue ticket related to srtm. But there is more complicated situation to implement static api.

**Comment by Hadatko** [comment]
Any update here?

**Comment by Hadatko** [comment]
@mcuxsusan i see that this lpm.c file is also located in https://github.com/NXPmicro/mcux-sdk-examples so i am moving there.

**Comment by Hadatko** [comment]
Clossing as PR was created here: https://github.com/NXPmicro/mcux-sdk-examples/pull/4
