### ISSUE TITLE
Eliminate differences between various MCUXpresso SDKs

### ISSUE THREAD

**Issue by dsyx** [NXPmicro/mcux-sdk#82]
Currently, there are three ways to obtain the MCUXpresso SDK:

* [MCUXpresso SDK Builder](https://mcuxpresso.nxp.com/en/), 'BuilderSDK' for short
* [MCUXpresso IDE](https://www.nxp.com/design/software/development-software/mcuxpresso-software-and-tools-/mcuxpresso-integrated-development-environment-ide:MCUXpresso-IDE), 'IDESDK' for short
* [GitHub](https://github.com/NXPmicro/mcux-sdk), 'GitHubSDK' for short

I want to configure a general development environment based on VSCode + CMake + GNU Arm Embedded Toolchain for NXP MCU. However, none of these three SDKs are perfect for me:

* GitHubSDK contains code for various devices, but lacks a lot of middleware compared to the other two SDKs.
* The BuilderSDK can only select a single device or board to build, I may need to configure the workspace environment for each device or board individually.

Is there a way to build a BuilderSDK for multiple devices/boards or to complement the middleware that GitHubSDK is missing?

Thanks

**Comment by mcuxsusan** [comment]
Hi @dsyx, unfortunately we do not have the way to get all devices/boards with full middleware support for now. We are still in the way enriching GitHub SDK to put more middleware, but that's not a short-term thing.

**Comment by dsyx** [comment]
Hi @mcuxsusan ,
It does take a long time to migrate middleware. So is there a way to make the BuilderSDK support multiple devices/boards?

**Comment by mcuxsusan** [comment]
> Hi @mcuxsusan , It does take a long time to migrate middleware. So is there a way to make the BuilderSDK support multiple devices/boards?

Hi, the SDK Builder only provides SDK for single board, because customers mostly only working on single device. I appreciate your effort on creating ecosystem for all users to ease their development on all NXP MCUs, this matches our design of GitHub SDK in which we provide a superset of board/device support.

**Comment by dsyx** [comment]
Thanks for your answer.
