### ISSUE TITLE
Better VSCode+CMake Tools experience

### ISSUE THREAD

**Issue by dsyx** [NXPmicro/mcux-sdk#83]
Based on this project, I tried to create a VSCode + CMake + GNU Arm Embedded Toolchain development environment ([mcuxsdk-vscode](https://github.com/dsyx/mcuxsdk-vscode)), including:

* Build executable
* Flash the executable to the device
* Debug executable

Currently this works fine.

In the process of developing [mcuxsdk-vscode](https://github.com/dsyx/mcuxsdk-vscode), I found some points that can be improved in this project:

* The build output of the example project uses `${PROJECT_BINARY_DIR}/${CMAKE_BUILD_TYPE}` to be more flexible than `${ProjDirPath}/${CMAKE_BUILD_TYPE}`.
* The example project should have its build output ignored from git.
* The example project should generate a hex file after building to facilitate user flashing to the device.
* Move the CMakeLists.txt of the example project to the example root directory to make it more suitable for VSCode Multi-root Workspaces.
* Add the appropriate CMakePresets.json to the example project to make the CMake Tools plugin work better.
* The Zephyr west tool is a good tool, but when I make changes to the repositories it manages, I don't know how to commit and track.

If you are interested in my idea, you can try [mcuxsdk-vscode](https://github.com/dsyx/mcuxsdk-vscode). You can use VSCode to open [mcuxsdk-vscode](https://github.com/dsyx/mcuxsdk-vscode)'s `vscode-ws/examples-evkbmimxrt1060.code-workspace` and `vscode-ws/examples-ok1061s.code-workspace` and compare their `led_blinky`.

Thanks

**Comment by mcuxsusan** [comment]
Thanks for the information, we will try the [mcuxsdk-vscode](https://github.com/dsyx/mcuxsdk-vscode) and get back to you later. Appreciate for your patience.
