### ISSUE TITLE
Component_serial_manager problem

### ISSUE THREAD

**Issue by Wielebny666** [NXPmicro/mcux-sdk#93]
Hi,
dupliacate case:

https://github.com/NXPmicro/mcux-sdk/blob/6e2aa2e7202503e49c0ca8adedaf026b06da90c1/components/serial_manager/fsl_component_serial_manager.c#L1261

https://github.com/NXPmicro/mcux-sdk/blob/6e2aa2e7202503e49c0ca8adedaf026b06da90c1/components/serial_manager/fsl_component_serial_manager.c#L1282

**Comment by mcuxsusan** [comment]
Hi @Wielebny666, thanks for reporting the issue. The development team noticed this issue and the fix will be applied soon.

**Comment by mcuxsusan** [comment]
Issue resolved at commit https://github.com/NXPmicro/mcux-sdk/commit/087e39de46415c5a8003f257ebca06f6e8fa8ef5
